kind: Pod
apiVersion: v1
metadata:
  name: multi-container
spec:
  containers:
# Since we are running multiple containers we are using list here.
  - name: nginx
    image: nginx
  - name: alma
    image: "almalinux:9"
    command: ["sleep", "1000"]