kind: pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        # Soft limit.
        requests:
          cpu: "100m"
          memory: "128Mi"
        # Hard limit. Should always be same as requests or more than the requests.
        limits:
          cpu: "101m"
          memory: "128Mi"