kind: pod
apiVersion: v1
metadata:
  name: pod-secrets
spec:
  containers:
    - name: nginx
      image: nginx
      # To refer individual value of secret from the secrets.
      env:
      - name: author
        valueFrom:
          secretKeyRef:
            name: secrets
            key: author
      # To refer all the secrets from the secrets.
      envFrom:
        secretRef:
          name: secrets